### ISSUE TITLE
 [ERROR] Internal Failure: il2cpp_init detour failed: One of the dependent libraries is missing.

### ISSUE THREAD

**Issue by BigCement** [Baydock/BTD6EpicGamesModCompat#6]
I installed melon, installed the mod helper, put it in mods folder, and after I got the error, downloaded the dotnet file, but it still did not fix it. Do I need to run the dotnet file or anything?

**Comment by SpiringRhino424** [comment]
I installed melon loader and mod helper and now it won't let me in. do anybody know how to fix it?

**Comment by Baydock** [comment]
you need to run the exe you download from https://dot.net

**Comment by Baydock** [comment]
dotnet 6 specifically

**Comment by TacticalNuke974** [comment]
I have the same issue with melon loader. How did you guys get it fixed? I don't know what that link does it just takes me to some basic website
